// STEP/DIR stepper control for 1..6 axes (spec §7.2, §12, §13).
//
// On the ESP32 the step pulses are generated by the FastAccelStepper hardware
// engine (RMT / MCPWM + timer), NOT from loop(), so timing is deterministic and
// independent of Wi-Fi / web / I²C latency. FastAccelStepper also does the
// trapezoidal accel/decel in hardware (fed from maxSpeedMmS / maxAccelMmS2);
// the pure MotionPlanner remains the host-tested reference model. Homing uses
// runForward/runBackward for the seeks and moveTo for the back-off/offset.
#pragma once

#include <cstdint>
#include <vector>

#include "../../core/instrument/ActuatorResult.h"
#include "../../core/motion/MotionPlanner.h"
#include "../../core/motion/StepperAxis.h"
#include "../../core/util/Debounce.h"

#if defined(ARDUINO)
#include <Arduino.h>
#include <FastAccelStepper.h>
#endif

namespace gmb {

struct AxisPins {
    int8_t step = -1;
    int8_t dir = -1;
    int8_t home = -1;
    int8_t limit = -1;
};

// The electrical half of an axis's endstops: how to read the pins, not what to do
// with them. Polarity used to arrive as two parallel `vector<bool>` and the
// debounce was a constant compiled in here; adding the sensor technology as a third
// and fourth parallel vector is how call sites start passing the LIMIT polarity in
// the HOME slot. One struct per axis, filled from that axis's HomingConfig.
struct AxisEndstops {
    bool homeActiveHigh = false;
    bool limitActiveHigh = false;
    // Milliseconds the level must hold before it is believed. Derived from the
    // sensor type via endstopDebounceMs(); 0 = take the sample as it comes.
    uint8_t homeDebounceMs = 3;
    uint8_t limitDebounceMs = 3;
};

class StepperBank {
public:
    // `endstops[i]` describes axis i's HOME/LIMIT inputs (polarity + settling
    // time), built from its homing config. homeActive()/limitActive() are
    // normalised through it; a missing entry means active-low with the mechanical
    // debounce — the common endstop wiring.
    void begin(const std::vector<AxisConfig>& axes,
               const std::vector<AxisPins>& pins, int8_t enablePin,
               const std::vector<AxisEndstops>& endstops = {});

    // Sample & debounce the HOME/LIMIT inputs. Call once per loop() before
    // reading homeActive()/limitActive()/homeRawHigh().
    void updateSensors(uint32_t nowMs);

    void enableDrivers(bool on);
    bool enabled() const { return enabled_; }

    // Position-mode move to an absolute target (mm, soft-limited). Returns an
    // ActuatorResult like every other actuator command (audit P1.4), so the
    // playback scheduler always knows whether the move reached the step engine and,
    // on failure, why — a refused move must fault the axis, never be assumed done.
    //   InvalidIndex : no such axis
    //   Disabled     : the profile disabled this axis
    //   OutputFault  : the axis never attached a hardware step generator
    ActuatorResult moveToMm(size_t axis, double mm);
    // Same but without soft-limit clamping (used during homing).
    ActuatorResult moveToMmRaw(size_t axis, double mm);
    // Velocity-mode cruise at a signed speed (mm/s), used by homing seeks.
    ActuatorResult setVelocityMm(size_t axis, double mmS);
    void stop(size_t axis);          // decelerated stop (normal musical stop)
    void emergencyStop(size_t axis); // immediate hard stop (LIMIT / E-stop)
    void stopAll();

    // Immediate HARD STOP of the whole bank (E-stop / panic / major fault): every
    // axis force-stopped where it stands and the shared driver ENABLE dropped, with
    // no deceleration ramp and no dependency on a move completing first
    // (spec P0 §21.2 — the motion-side twin of ServoBank::hardStop).
    void hardStop();

    // Controlled stop of the whole bank: every axis is asked for a DECELERATED stop
    // and the drivers stay enabled, so the carriages come to rest without losing
    // steps. The caller times the deceleration (stopDurationMs()) and only then cuts
    // ENABLE. Used for a normal stop / profile change — never for an E-stop.
    void controlledStopAll();

    // Worst-case ms for a decelerated stop from full speed across all enabled axes
    // (v/a, rounded up), i.e. how long controlledStopAll() needs before the
    // carriages are guaranteed still. 0 when nothing can move.
    uint32_t stopDurationMs() const;

    // Redefine the current physical position as `mm` (homing anchors home = 0).
    void setPositionReference(size_t axis, double mm);

    double positionMm(size_t axis) const;
    bool atTarget(size_t axis) const;   // motor stopped (used for "is it still?")
    // Stopped AND actually within tolerance of the last commanded position move —
    // a refused/interrupted move does not count as "arrived at the fret".
    bool reachedTarget(size_t axis) const;
    bool isRunning(size_t axis) const;  // true while the step engine is moving
    bool homeActive(size_t axis) const;   // normalised active-low reading
    bool homeRawHigh(size_t axis) const;  // raw level (polarity-aware homing)
    bool limitActive(size_t axis) const;

    // True if any ENABLED axis could not attach a hardware step generator.
    bool attachFault() const { return attachFault_; }
    // Per-axis attach fault (a disabled axis is never faulted here).
    bool axisAttachFault(size_t axis) const {
        return axis < axes_.size() && axes_[axis].attachFault;
    }

    // No-op on hardware (engine generates steps); kept for interface symmetry.
    void tick(uint32_t nowUs) { (void)nowUs; }

    size_t count() const { return axes_.size(); }
    // Cumulative position moves actually accepted by the step engine (diagnostics,
    // P2.19). Velocity cruises (homing seeks) are not counted — they are not
    // musical carriage moves.
    uint32_t moveCount() const { return moveCount_; }
    // Governor bucket for an axis. Steppers hang off their own STEP/DIR drivers,
    // not a PCA9685, so they share no per-board power window with the servos:
    // 0xFF means "only the global concurrency cap applies" (see ActuatorManager).
    uint8_t board(size_t axis) const { (void)axis; return 0xFF; }

private:
    struct AxisRt {
        StepperAxis geom;
        AxisPins pins;
        double stepsPerMm = 80.0;
        long position = 0;  // used by the non-Arduino stub only
        double cmdTargetMm = 0.0;  // last commanded position-move target
        bool hasTarget = false;
        bool homeActiveHigh = false;
        bool limitActiveHigh = false;
        bool attachFault = false;  // this enabled axis could not attach a generator
        Debouncer homeDeb;   // debounced raw HIGH level of the HOME pin
        Debouncer limitDeb;  // debounced raw HIGH level of the LIMIT pin
        AxisRt(const AxisConfig& c) : geom(c) {}
    };
    // Can this axis accept a motion command at all? Ok, or the reason not.
    ActuatorResult axisWritable(size_t axis) const;

    std::vector<AxisRt> axes_;
    int8_t enablePin_ = -1;
    bool enabled_ = false;
    bool attachFault_ = false;
    uint32_t moveCount_ = 0;  // cumulative accepted position moves (diagnostics)

#if defined(ARDUINO)
    FastAccelStepperEngine engine_;
    std::vector<FastAccelStepper*> steppers_;
#endif
};

}  // namespace gmb
