/*
 * boarddata.js — GENERATED, do not edit by hand.
 *
 * Board capability tables for the offline mock backend, rendered from
 * firmware/src/core/board/BoardProfile.cpp by
 * firmware/tools/dump_board_profiles.cpp. Edit the C++ tables and run
 * firmware/test/boardcheck/run.sh; CI checks this file with --check.
 *
 * On a real device these come from GET /api/boards and /api/board/{id};
 * this file is what makes the file:// demo behave the same.
 */
(function (global) {
  'use strict';
  var GMB = global.GMB = global.GMB || {};
  GMB.BOARD_PROFILES = [
    {
      identifier: "esp32-s3-devkitc-1",
      displayName: "ESP32-S3-DevKitC-1 v1.0 (RGB LED on GPIO48)",
      recommendedAssignment: {
        STEP: [4, 5, 6, 7, 15, 16],
        DIR: [17, 18, 8, 9, 10, 11],
        HOME: [12, 13, 14, 21, 38, 39],
        SDA: 40, SCL: 41, ENABLE: 42, SERVO_OE: 47
      },
      pins: [
        { gpio: 0, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping / BOOT button — forces the Wi-Fi hotspot (P1.15)" },
        { gpio: 1, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 2, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 3, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 4, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 5, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 6, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 7, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 8, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 9, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 10, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 11, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 12, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 13, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 14, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 15, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 16, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 17, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 18, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 19, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: true, onboardPeripheral: false, preference: "reserved", note: "USB-JTAG / native USB D-" },
        { gpio: 20, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: true, onboardPeripheral: false, preference: "reserved", note: "USB-JTAG / native USB D+" },
        { gpio: 21, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 26, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 27, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 28, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 29, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 30, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 31, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 32, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 33, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "May be tied to Flash/PSRAM on some module variants" },
        { gpio: 34, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "May be tied to Flash/PSRAM on some module variants" },
        { gpio: 35, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 36, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 37, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 38, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 39, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 40, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SDA" },
        { gpio: 41, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SCL" },
        { gpio: 42, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 43, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 TX (programming / diagnostics)" },
        { gpio: 44, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 RX (programming / diagnostics)" },
        { gpio: 45, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 46, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 47, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 48, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "On-board RGB LED (DevKitC-1 v1.0)" }
      ]
    },
    {
      identifier: "esp32-s3-devkitc-1-v1.1",
      displayName: "ESP32-S3-DevKitC-1 v1.1 (RGB LED on GPIO38)",
      recommendedAssignment: {
        STEP: [4, 5, 6, 7, 15, 16],
        DIR: [17, 18, 8, 9, 10, 11],
        HOME: [12, 13, 14, 21, 38, 39],
        SDA: 40, SCL: 41, ENABLE: 42, SERVO_OE: 47
      },
      pins: [
        { gpio: 0, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping / BOOT button — forces the Wi-Fi hotspot (P1.15)" },
        { gpio: 1, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 2, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 3, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 4, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 5, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 6, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 7, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 8, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 9, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 10, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 11, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 12, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 13, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 14, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 15, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 16, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 17, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 18, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 19, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: true, onboardPeripheral: false, preference: "reserved", note: "USB-JTAG / native USB D-" },
        { gpio: 20, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: true, onboardPeripheral: false, preference: "reserved", note: "USB-JTAG / native USB D+" },
        { gpio: 21, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 26, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 27, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 28, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 29, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 30, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 31, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 32, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Reserved for on-chip Flash / PSRAM" },
        { gpio: 33, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "May be tied to Flash/PSRAM on some module variants" },
        { gpio: 34, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "May be tied to Flash/PSRAM on some module variants" },
        { gpio: 35, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 36, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 37, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Octal Flash/PSRAM on some variants — verify module" },
        { gpio: 38, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "On-board RGB LED (DevKitC-1 v1.1)" },
        { gpio: 39, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 40, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SDA" },
        { gpio: 41, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SCL" },
        { gpio: 42, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 43, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 TX (programming / diagnostics)" },
        { gpio: 44, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 RX (programming / diagnostics)" },
        { gpio: 45, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 46, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "Strapping pin" },
        { gpio: 47, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 48, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" }
      ]
    },
    {
      identifier: "esp32-wroom-32",
      displayName: "ESP32-WROOM-32 (DevKitC, 38-pin)",
      recommendedAssignment: {
        STEP: [4, 13, 14, 25],
        DIR: [26, 27, 32, 33],
        HOME: [16, 17, 18, 19],
        SDA: 21, SCL: 22, ENABLE: 23, SERVO_OE: 5
      },
      pins: [
        { gpio: 0, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "BOOT button — forces the Wi-Fi hotspot; never a signal pin" },
        { gpio: 1, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 TX (programming / diagnostics)" },
        { gpio: 2, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "Strapping / on-board LED on many boards" },
        { gpio: 3, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 RX (programming / diagnostics)" },
        { gpio: 4, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 5, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "Strapping pin (must be HIGH at boot)" },
        { gpio: 6, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 7, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 8, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 9, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 10, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 11, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: false, preference: "reserved", note: "Connected to the SPI flash" },
        { gpio: 12, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "MTDI strapping pin (flash voltage)" },
        { gpio: 13, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 14, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 15, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "MTDO strapping pin" },
        { gpio: 16, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Used by PSRAM on WROVER modules — verify yours" },
        { gpio: 17, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Used by PSRAM on WROVER modules — verify yours" },
        { gpio: 18, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 19, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 21, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SDA" },
        { gpio: 22, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SCL" },
        { gpio: 23, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended PCA9685 /OE" },
        { gpio: 25, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 26, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 27, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 32, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 33, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 34, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot drive an output, and needs an external pull-up" },
        { gpio: 35, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot drive an output, and needs an external pull-up" },
        { gpio: 36, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only sensor VP (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot output" },
        { gpio: 39, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only sensor VN (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot output" }
      ]
    },
    {
      identifier: "esp32-devkit-v1",
      displayName: "ESP32 DevKit v1 (30-pin)",
      recommendedAssignment: {
        STEP: [4, 13, 14, 25],
        DIR: [26, 27, 32, 33],
        HOME: [16, 17, 18, 19],
        SDA: 21, SCL: 22, ENABLE: 23, SERVO_OE: 5
      },
      pins: [
        { gpio: 0, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: true, usb: false, onboardPeripheral: false, preference: "reserved", note: "BOOT button — forces the Wi-Fi hotspot; never a signal pin" },
        { gpio: 1, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 TX (programming / diagnostics)" },
        { gpio: 2, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "Strapping / on-board LED on many boards" },
        { gpio: 3, exposed: true, input: true, output: true, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: false, reserved: true, strapping: false, usb: false, onboardPeripheral: true, preference: "reserved", note: "UART0 RX (programming / diagnostics)" },
        { gpio: 4, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 5, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "Strapping pin (must be HIGH at boot)" },
        { gpio: 12, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "MTDI strapping pin (flash voltage)" },
        { gpio: 13, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 14, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 15, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: true, usb: false, onboardPeripheral: false, preference: "caution", note: "MTDO strapping pin" },
        { gpio: 16, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Used by PSRAM on WROVER modules — verify yours" },
        { gpio: 17, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Used by PSRAM on WROVER modules — verify yours" },
        { gpio: 18, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 19, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 21, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SDA" },
        { gpio: 22, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended I2C SCL" },
        { gpio: 23, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: false, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "Recommended PCA9685 /OE" },
        { gpio: 25, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 26, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 27, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 32, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 33, exposed: true, input: true, output: true, interrupt: true, internalPullUp: true, internalPullDown: true, highSpeedOutput: true, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "recommended", note: "" },
        { gpio: 34, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot drive an output, and needs an external pull-up" },
        { gpio: 35, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot drive an output, and needs an external pull-up" },
        { gpio: 36, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only sensor VP (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot output" },
        { gpio: 39, exposed: true, input: true, output: false, interrupt: true, internalPullUp: false, internalPullDown: false, highSpeedOutput: false, adc: true, reserved: false, strapping: false, usb: false, onboardPeripheral: false, preference: "caution", note: "Input-only sensor VN (ADC1), no internal pull-up — read-only signals such as MIDI_RX; cannot output" }
      ]
    }
  ];
})(window);
