#!/usr/bin/env python3
"""Embed the web interface into the firmware binary.

Reads every file under web-interface/ (except README.md), gzip-compresses it,
and regenerates firmware/src/platform/esp32/WebAssets.cpp — a table of
{path, mime, bytes} the firmware serves from flash whenever LittleFS /www does
not provide the file. The generated file is COMMITTED, so a plain Arduino IDE
"Upload" (or `pio run -t upload`) ships a working web UI with no separate
filesystem-upload step; uploading LittleFS remains an optional per-file
override (serveStatic has first pick).

Run whenever web-interface/ changes (sync_web_data.sh calls this too):

    python3 firmware/tools/embed_web_assets.py

The output is deterministic (sorted paths, fixed gzip header) so CI can verify
the committed file matches the sources with a plain `git diff`.
"""

import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent / "web-interface"
OUT = HERE.parent / "src" / "platform" / "esp32" / "WebAssets.cpp"

SKIP = {"README.md"}
# Directories never shipped to the device (dev-only content: the Node behavioural
# tests under web-interface/test/ and the maintenance scripts under
# web-interface/tools/, e.g. the screenshot capture).
SKIP_DIRS = {"test", "tools"}

MIME = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".woff2": "font/woff2",
    ".map": "application/json",
    ".txt": "text/plain",
}


def gzip_deterministic(data: bytes) -> bytes:
    """gzip -9 with a fixed header (mtime 0, no name, OS unknown) so the output
    depends only on the input bytes, never on the clock or the Python version."""
    co = zlib.compressobj(9, zlib.DEFLATED, -15)  # raw deflate
    body = co.compress(data) + co.flush()
    header = b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff"
    crc = zlib.crc32(data) & 0xFFFFFFFF
    size = len(data) & 0xFFFFFFFF
    return header + body + crc.to_bytes(4, "little") + size.to_bytes(4, "little")


def emit_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = ",".join(f"0x{b:02x}" for b in data[i : i + 16])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def main() -> int:
    if not SRC.is_dir():
        print(f"error: web-interface/ not found at {SRC}", file=sys.stderr)
        return 1

    files = sorted(
        p for p in SRC.rglob("*")
        if p.is_file() and p.name not in SKIP
        and not (SKIP_DIRS & set(p.relative_to(SRC).parts[:-1]))
    )
    if not files:
        print(f"error: no files under {SRC}", file=sys.stderr)
        return 1

    assets = []  # (url path, mime, payload, gzipped, raw size)
    for p in files:
        rel = "/" + p.relative_to(SRC).as_posix()
        mime = MIME.get(p.suffix.lower(), "application/octet-stream")
        raw = p.read_bytes()
        gz = gzip_deterministic(raw)
        # Keep gzip only when it actually shrinks (PNG & friends usually don't).
        if len(gz) < len(raw):
            assets.append((rel, mime, gz, True, len(raw)))
        else:
            assets.append((rel, mime, raw, False, len(raw)))

    total = sum(len(a[2]) for a in assets)
    out = []
    out.append("// AUTO-GENERATED by firmware/tools/embed_web_assets.py — DO NOT EDIT.")
    out.append("//")
    out.append("// Embedded copy of web-interface/ (gzip-compressed), served from flash when")
    out.append("// LittleFS /www does not provide the file — so a plain firmware upload ships")
    out.append("// a working web UI. Regenerate (and commit) whenever web-interface/ changes:")
    out.append("//     python3 firmware/tools/embed_web_assets.py   (sync_web_data.sh runs it too)")
    out.append(f"// {len(assets)} assets, {total} bytes embedded.")
    out.append('#include "WebAssets.h"')
    out.append("")
    out.append("#include <cstring>")
    out.append("")
    out.append("namespace gmb {")
    out.append("namespace {")
    for i, (rel, _mime, payload, gzipped, raw_len) in enumerate(assets):
        note = f"{raw_len} -> {len(payload)} bytes gzip" if gzipped else f"{raw_len} bytes raw"
        out.append(f"// {rel} ({note})")
        out.append(f"const uint8_t kAsset{i}[] = {{")
        out.append(emit_bytes(payload))
        out.append("};")
    out.append("")
    out.append("const WebAsset kAssets[] = {")
    for i, (rel, mime, payload, gzipped, _raw_len) in enumerate(assets):
        gz = "true" if gzipped else "false"
        out.append(f'    {{"{rel}", "{mime}", kAsset{i}, sizeof(kAsset{i}), {gz}}},')
    out.append("};")
    out.append("}  // namespace")
    out.append("")
    out.append("const WebAsset* findWebAsset(const char* path) {")
    out.append("    if (path == nullptr) return nullptr;")
    out.append("    for (const WebAsset& a : kAssets)")
    out.append("        if (std::strcmp(a.path, path) == 0) return &a;")
    out.append("    return nullptr;")
    out.append("}")
    out.append("")
    out.append("}  // namespace gmb")
    out.append("")

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Embedded {len(assets)} web assets ({total} bytes) -> {OUT.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
